# docker build -f docker/Dockerfile.base -t det .
#from node:6
from mhart/alpine-node:4

# Use yarn
arg YARN_VERSION=0.18.0
env YARN_VERSION=$YARN_VERSION
add pkg/yarn-v${YARN_VERSION}.tar.gz /opt
run mv /opt/dist /opt/yarn
#//run npm install --no-cache --production -g yarn

# Install app
workdir /app
copy package.json /app/package.json
copy yarn.lock /app/yarn.lock
run set -uex; \
    /opt/yarn/bin/yarn install --prod --cache-folder /dev/.yarn-cache; \
    rm -rf /dev/.yarn-cache; \
    find /app
add pkg/deployable-template.tar /app
 
entrypoint [ "/app/bin/det" ]
cmd [ "" ]

