# docker build -f docker/Dockerfile -t dmod .
#from node:6
from mhart/alpine-node:7

# Use yarn
arg YARN_VERSION=0.18.0
env YARN_VERSION=$YARN_VERSION
add pkg/yarn-v$YARN_VERSION.tar.gz /opt
run mv /opt/dist /opt/yarn
#//run npm install --no-cache --production -g yarn

# Install app
add pkg/deployable-template.tar.gz /app
workdir /app
run set -uex; \
    rm -rf /app/docker; \
    /opt/yarn/bin/yarn install --prod --cache-folder /dev/.yarn-cache; \
    rm -rf /dev/.yarn-cache; \
    find /app
 
entrypoint [ "/app/bin/dt" ]
cmd [ "" ]

